import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'uz' | 'ru' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  uz: {
    'menu.home': 'Bosh sahifa',
    'menu.blog': 'Blog',
    'menu.profile': 'Profil',
    'menu.admin': 'Boshqaruv paneli',
    'menu.stats': 'Statistika',
    'menu.help': 'Yordam',
    'menu.logout': 'Chiqish',
    'menu.login': 'Kirish',
    'menu.title': 'Menyu',
    'menu.subtitle': 'TezChipta xizmatlari',
    'lang.uz': "O'zbekcha",
    'lang.ru': 'Русский',
    'lang.en': 'English',
    'lang.select': 'Tilni tanlang',
    'home.hero.title': "Xorazmdan Toshkentga",
    'home.hero.highlight': "tez, qulay va arzon",
    'home.hero.action': "chipta sotib oling!",
    'home.hero.subtitle': "1 daqiqada o'rindiq tanlang, haydovchi bilan bog'laning, chiptani onlayn sotib oling.",
    'home.search.from_label': 'Qayerdan',
    'home.search.to_label': 'Qayerga',
    'home.search.date_label': 'Sana',
    'home.search.all_cities': 'Barcha shaharlar',
    'home.search.btn': 'Qidirish',
    'home.search.from': 'Qayerdan?',
    'home.search.to': 'Qayerga?',
    'home.search.today': 'Bugun',
    'home.search.tomorrow': 'Ertaga',
    'home.search.weekly': 'Haftalik',
    'home.rides.title': 'Mavjud qatnovlar',
    'home.rides.empty': 'Hozircha qatnovlar mavjud emas',
    'home.booking.btn': 'Chipta olish',
    'home.faq.title': 'Ko\'p beriladigan savollar',
    'profile.track_bus': 'Kuzatish',
    'profile.driver_controls': 'Haydovchi boshqaruvi',
    'profile.share_location': 'Manzilni ulashish',
    'profile.bus_location_title': 'Avtobus qayerda?',
    'profile.live_tracking': 'Real vaqt rejimida kuzatish',
    'profile.live_status': 'Jonli efir',
    'profile.location_not_found': 'Manzil aniqlanmadi',
    'profile.driver_not_sharing': 'Haydovchi hali o\'z manzilini ulashmadi.',
    'profile.loading_map': 'Xarita yuklanmoqda...',
    'home.rides.subtitle': "Eng mos vaqtni tanlang va o'z o'rningizni band qiling.",
    'home.rides.loading': "Qatnovlar qidirilmoqda...",
    'home.rides.recommended': "Tavsiya etiladi",
    'home.rides.price': "Chipta narxi",
    'home.rides.departure': "Jo'nash",
    'home.rides.arrival': "Kelish",
    'home.rides.seats_left': "ta o'rin qoldi",
    'home.rides.book_btn': "O'rindiq tanlash",
    'home.rides.driver': "Haydovchi",
    'home.rides.bus_info': "Avtobus ma'lumotlari",
    'home.rides.amenities': "Qulayliklar",
    'home.rides.wifi': "Wi-Fi",
    'home.rides.ac': "Konditsioner",
    'home.rides.tv': "TV",
    'home.rides.socket': "Rozetka",
    'home.rides.water': "Suv",
    'home.rides.select_seat': "O'rindiqni tanlang",
    'home.rides.selected_seat': "Tanlangan o'rindiq",
    'home.rides.continue': "Davom etish",
    'home.rides.cancel': "Bekor qilish",
    'home.payment.title': "To'lov usulini tanlang",
    'home.payment.card': "Karta orqali (Stripe)",
    'home.payment.manual': "Karta raqamiga o'tkazish",
    'home.payment.manual_desc': "Quyidagi karta raqamiga pul o'tkazing va chekni yuklang",
    'home.payment.upload_receipt': "Chekni yuklash",
    'home.payment.confirm': "To'lovni tasdiqlash",
    'home.payment.success': "To'lov muvaffaqiyatli amalga oshirildi!",
    'home.payment.processing': "To'lov tekshirilmoqda...",
    'home.payment.error': "To'lovda xatolik yuz berdi",
    'home.contact.title': "Biz bilan bog'lanish",
    'home.contact.subtitle': "Savollaringiz bormi? Bizga yozing",
    'home.contact.name': "Ismingiz",
    'home.contact.contact': "Telefon yoki Email",
    'home.contact.message': "Xabaringiz",
    'home.contact.send': "Yuborish",
    'home.contact.success': "Xabaringiz yuborildi!",
    'home.reviews.title': "Mijozlar fikrlari",
    'home.reviews.subtitle': "Bizning xizmatlarimiz haqida mijozlarimiz nima deydi?",
    'home.reviews.add': "Fikr qoldirish",
    'home.reviews.rating': "Baho",
    'home.reviews.comment': "Fikringiz",
    'home.reviews.submit': "Yuborish",
    'home.stats.passengers': "Yo'lovchilar",
    'home.stats.routes': "Qatnovlar",
    'home.stats.drivers': "Haydovchilar",
    'home.stats.experience': "Yillik tajriba",
    'home.footer.about': "TezChipta - O'zbekiston bo'ylab xavfsiz va qulay avtobus qatnovlari.",
    'home.features.title': "Nega aynan biz?",
    'home.features.subtitle': "Biz bilan sayohat qilishning afzalliklari",
    'home.features.f1_title': "Tez va qulay",
    'home.features.f1_desc': "Chiptalarni uydan chiqmasdan, 1 daqiqada xarid qiling.",
    'home.features.f2_title': "Xavfsiz to'lov",
    'home.features.f2_desc': "Barcha to'lovlar himoyalangan va xavfsiz.",
    'home.features.f3_title': "24/7 Qo'llab-quvvatlash",
    'home.features.f3_desc': "Har qanday savol bo'yicha yordam berishga tayyormiz.",
    'home.features.f4_title': "Qulay avtobuslar",
    'home.features.f4_desc': "Barcha avtobuslarimiz zamonaviy va qulayliklarga ega.",
    'auth.login.title': "Xush kelibsiz",
    'auth.login.subtitle': "Tizimga kirish uchun ma'lumotlaringizni kiriting",
    'auth.login.email_tab': "Email orqali",
    'auth.login.phone_tab': "Telefon orqali",
    'auth.login.email_label': "Email manzil",
    'auth.login.phone_label': "Telefon raqam",
    'auth.login.password_label': "Parol",
    'auth.login.forgot_password': "Parolni unutdingizmi?",
    'auth.login.btn': "Tizimga kirish",
    'auth.login.google_btn': "Google orqali kirish",
    'auth.login.no_account': "Hisobingiz yo'qmi?",
    'auth.login.register_link': "Ro'yxatdan o'tish",
    'auth.login.send_code': "Kodni yuborish",
    'auth.login.verify_code': "Kodni tasdiqlash",
    'auth.login.code_label': "Tasdiqlash kodi",
    'auth.login.back': "Orqaga",
    'auth.register.title': "Ro'yxatdan o'tish",
    'auth.register.subtitle': "Yangi hisob yaratish uchun ma'lumotlarni kiriting",
    'auth.register.name_label': "Ism va familiya",
    'auth.register.role_label': "Kim sifatida ro'yxatdan o'tmoqchisiz?",
    'auth.register.role_user': "Yo'lovchi",
    'auth.register.role_driver': "Haydovchi",
    'auth.register.btn': "Ro'yxatdan o'tish",
    'auth.register.has_account': "Hisobingiz bormi?",
    'auth.register.login_link': "Tizimga kirish",
    'profile.title': "Shaxsiy kabinet",
    'profile.subtitle': "Ma'lumotlaringiz va chiptalaringiz",
    'profile.tabs.tickets': "Faol chiptalar",
    'profile.tabs.history': "Tarix",
    'profile.tabs.newsletter': "Newsletter",
    'profile.tabs.settings': "Sozlamalar",
    'profile.tickets.empty': "Sizda hozircha faol chiptalar yo'q",
    'profile.tickets.find': "Qatnovlarni izlash",
    'profile.history.empty': "Sayohatlar tarixi bo'sh",
    'profile.settings.name': "Ism va familiya",
    'profile.settings.phone': "Telefon raqam",
    'profile.settings.email': "Email",
    'profile.settings.save': "Saqlash",
    'profile.settings.success': "Ma'lumotlar saqlandi!",
    'profile.ticket.download': "Yuklab olish",
    'profile.ticket.cancel': "Bekor qilish",
    'profile.ticket.status.pending': "Kutilmoqda",
    'profile.ticket.status.confirmed': "Tasdiqlangan",
    'profile.ticket.status.cancelled': "Bekor qilingan",
    'profile.ticket.seat': "O'rindiq",
    'profile.ticket.price': "Narxi",
    'profile.ticket.date': "Xarid",
    'profile.driver.rides': "Mening qatnovlarim",
    'profile.driver.add_ride': "Qatnov qo'shish",
    'profile.driver.stop_sharing': "To'xtatish",
    'home.faq.q1': "Chiptani qanday bekor qilish mumkin?",
    'home.faq.a1': "Profilingizdagi 'Faol chiptalar' bo'limiga kirib, kerakli chiptani tanlang va bekor qilish tugmasini bosing. Mablag'ingiz 3 ish kunida qaytariladi.",
    'home.faq.q2': "Bagaj qoidalari qanday?",
    'home.faq.a2': "Har bir yo'lovchi uchun 20 kg gacha bepul bagaj ruxsat etiladi. Qo'shimcha yuk uchun alohida to'lov amalga oshiriladi.",
    'home.faq.q3': "Haydovchi bilan qanday bog'lanish mumkin?",
    'home.faq.a3': "Chipta sotib olganingizdan so'ng, haydovchining telefon raqami profilingizdagi chipta ma'lumotlarida ko'rinadi.",
    'home.faq.q4': "To'lov qanday amalga oshiriladi?",
    'home.faq.a4': "To'lovlarni Payme, Click, UzCard va Humo tizimlari orqali onlayn tarzda amalga oshirishingiz mumkin.",
    'home.faq.q5': "O'rindiqni oldindan band qilish mumkinmi?",
    'home.faq.a5': "Ha, reysni tanlash jarayonida bo'sh o'rindiqlardan o'zingizga ma'qulini tanlab band qilishingiz mumkin.",
    'home.faq.q6': "Bolalar uchun chegirma bormi?",
    'home.faq.a6': "7 yoshgacha bo'lgan bolalar uchun 50% chegirma mavjud. 7 yoshdan yuqori bolalar uchun to'liq chipta narxi hisoblanadi.",
    'home.footer.desc': "Xorazmdan Toshkentga va qaytish yo'nalishida eng qulay, tez va xavfsiz avtobus qatnovlari.",
    'home.footer.links': "Tezkor havolalar",
    'home.footer.contact': "Bog'lanish",
    'home.footer.newsletter': "Yangiliklarga obuna bo'ling",
    'home.footer.newsletter_desc': "Chegirmalar va yangi reyslar haqida birinchilardan bo'lib xabardor bo'ling.",
    'home.footer.rights': "Barcha huquqlar himoyalangan.",
    'home.footer.privacy': "Maxfiylik siyosati",
    'home.footer.terms': "Ommaviy oferta",
    'admin.dashboard': 'Dashboard',
    'admin.rides': 'Qatnovlar',
    'admin.drivers': 'Haydovchilar',
    'admin.users': 'Foydalanuvchilar',
    'admin.messages': 'Xabarlar',
    'admin.chats': 'Chatlar',
    'admin.reviews': 'Fikrlar',
    'admin.payments': "To'lovlar",
    'admin.settings': 'Sozlamalar',
    'admin.faqs': 'FAQ',
    'admin.logout': 'Chiqish',
    'admin.rides.new': 'Yangi qatnov',
    'admin.rides.edit': 'Qatnovni tahrirlash',
    'admin.rides.add': "Qatnov qo'shish",
    'admin.drivers.new': 'Yangi haydovchi',
    'admin.drivers.edit': 'Haydovchini tahrirlash',
    'admin.drivers.add': "Haydovchi qo'shish",
    'admin.users.new': 'Yangi foydalanuvchi',
    'admin.users.edit': 'Foydalanuvchini tahrirlash',
    'admin.users.add': "Foydalanuvchi qo'shish",
    'admin.faqs.new': 'Yangi savol',
    'admin.faqs.edit': 'Savolni tahrirlash',
    'admin.faqs.add': "Savol qo'shish",
    'admin.common.save': 'Saqlash',
    'admin.common.delete': "O'chirish",
    'admin.common.cancel': 'Bekor qilish',
    'admin.common.actions': 'Amallar',
    'admin.common.status': 'Holati',
    'admin.common.date': 'Sana',
    'admin.common.price': 'Narxi',
    'admin.users.search': 'Foydalanuvchi qidirish...',
    'admin.users.role_user': 'Foydalanuvchi',
    'admin.users.role_driver': 'Haydovchi',
    'admin.users.role_admin': 'Admin',
    'admin.users.send_message': 'Xabar yozish',
    'admin.chats.create_error': 'Chat yaratishda xatolik yuz berdi',
    'admin.chats.title': 'Foydalanuvchilar bilan chat',
    'admin.chats.search': 'Chatlarni qidirish...',
    'admin.chats.input_placeholder': 'Xabar yozing...',
    'admin.chats.select_user': 'Suhbatni boshlash uchun chap tomondan foydalanuvchini tanlang',
    'admin.chats.online': 'Onlayn',
    'admin.chats.you_admin': 'Siz (Admin)',
    'admin.chats.email_not_found': 'Email mavjud emas',
    'home.reviews.empty': "Hozircha fikrlar yo'q",
    'home.reviews.login_to_review': "Fikr qoldirish uchun tizimga kiring",
    'home.faq.subtitle': "Barcha savollaringizga batafsil javoblar",
    'home.contact.success_desc': "Sizning xabaringiz muvaffaqiyatli yuborildi. Biz tez orada bog'lanamiz.",
    'home.hero.search': "Reyslarni izlash",
    'admin.notifications': 'Bildirishnomalar',
    'admin.notifications.new': 'Yangi bildirishnoma',
    'admin.notifications.send': 'Yuborish',
    'admin.notifications.cancel': 'Bekor qilish',
    'admin.notifications.form_title': 'Yangi bildirishnoma yuborish',
    'admin.notifications.title_label': 'Sarlavha',
    'admin.notifications.message_label': 'Xabar matni',
    'admin.notifications.target_label': 'Kimga yuborish',
    'admin.notifications.target_all': 'Barcha foydalanuvchilarga',
    'admin.notifications.target_newcomers': 'Yangi kelganlarga (0 chipta yoki &lt; 2 kun)',
    'admin.notifications.empty': 'Hozircha yuborilgan bildirishnomalar yo\'q.',
    'admin.notifications.sent_title': 'Yuborilgan bildirishnomalar',
  },
  ru: {
    'menu.home': 'Главная',
    'menu.blog': 'Блог',
    'menu.profile': 'Профиль',
    'menu.admin': 'Панель управления',
    'menu.stats': 'Статистика',
    'menu.help': 'Помощь',
    'menu.logout': 'Выйти',
    'menu.login': 'Войти',
    'menu.title': 'Меню',
    'menu.subtitle': 'Услуги TezChipta',
    'lang.uz': 'Узбекский',
    'lang.ru': 'Русский',
    'lang.en': 'Английский',
    'lang.select': 'Выберите язык',
    'home.hero.title': 'Из Хорезма в Ташкент',
    'home.hero.highlight': 'быстро, удобно и дешево',
    'home.hero.action': 'купите билет!',
    'home.hero.subtitle': 'Выберите место за 1 минуту, свяжитесь с водителем, купите билет онлайн.',
    'home.search.from_label': 'Откуда',
    'home.search.to_label': 'Куда',
    'home.search.date_label': 'Дата',
    'home.search.all_cities': 'Все города',
    'home.search.btn': 'Поиск',
    'home.search.from': 'Откуда?',
    'home.search.to': 'Куда?',
    'home.search.today': 'Сегодня',
    'home.search.tomorrow': 'Завтра',
    'home.search.weekly': 'На неделю',
    'home.rides.title': 'Доступные рейсы',
    'home.rides.empty': 'Рейсов пока нет',
    'home.booking.btn': 'Купить билет',
    'home.faq.title': 'Часто задаваемые вопросы',
    'profile.track_bus': 'Отследить',
    'profile.driver_controls': 'Управление водителем',
    'profile.share_location': 'Поделиться местоположением',
    'profile.bus_location_title': 'Где автобус?',
    'profile.live_tracking': 'Отслеживание в реальном времени',
    'profile.live_status': 'В прямом эфире',
    'profile.location_not_found': 'Местоположение не определено',
    'profile.driver_not_sharing': 'Водитель еще не поделился своим местоположением.',
    'profile.loading_map': 'Загрузка карты...',
    'home.rides.subtitle': "Выберите удобное время и забронируйте место.",
    'home.rides.loading': "Поиск рейсов...",
    'home.rides.recommended': "Рекомендуется",
    'home.rides.price': "Цена билета",
    'home.rides.departure': "Отправление",
    'home.rides.arrival': "Прибытие",
    'home.rides.seats_left': "мест осталось",
    'home.rides.book_btn': "Выбрать место",
    'home.rides.driver': "Водитель",
    'home.rides.bus_info': "Информация об автобусе",
    'home.rides.amenities': "Удобства",
    'home.rides.wifi': "Wi-Fi",
    'home.rides.ac': "Кондиционер",
    'home.rides.tv': "ТВ",
    'home.rides.socket': "Розетка",
    'home.rides.water': "Вода",
    'home.rides.select_seat': "Выберите место",
    'home.rides.selected_seat': "Выбранное место",
    'home.rides.continue': "Продолжить",
    'home.rides.cancel': "Отмена",
    'home.payment.title': "Выберите способ оплаты",
    'home.payment.card': "Картой (Stripe)",
    'home.payment.manual': "Перевод на карту",
    'home.payment.manual_desc': "Переведите деньги на номер карты ниже и загрузите чек",
    'home.payment.upload_receipt': "Загрузить чек",
    'home.payment.confirm': "Подтвердить оплату",
    'home.payment.success': "Оплата успешно завершена!",
    'home.payment.processing': "Проверка оплаты...",
    'home.payment.error': "Ошибка при оплате",
    'home.contact.title': "Свяжитесь с нами",
    'home.contact.subtitle': "Есть вопросы? Напишите нам",
    'home.contact.name': "Ваше имя",
    'home.contact.contact': "Телефон или Email",
    'home.contact.message': "Ваше сообщение",
    'home.contact.send': "Отправить",
    'home.contact.success': "Ваше сообщение отправлено!",
    'home.reviews.title': "Отзывы клиентов",
    'home.reviews.subtitle': "Что говорят наши клиенты о наших услугах?",
    'home.reviews.add': "Оставить отзыв",
    'home.reviews.rating': "Оценка",
    'home.reviews.comment': "Ваш отзыв",
    'home.reviews.submit': "Отправить",
    'home.stats.passengers': "Пассажиры",
    'home.stats.routes': "Рейсы",
    'home.stats.drivers': "Водители",
    'home.stats.experience': "Лет опыта",
    'home.footer.about': "TezChipta - Безопасные и комфортные автобусные рейсы по Узбекистану.",
    'home.features.title': "Почему мы?",
    'home.features.subtitle': "Преимущества путешествия с нами",
    'home.features.f1_title': "Быстро и удобно",
    'home.features.f1_desc': "Покупайте билеты не выходя из дома за 1 минуту.",
    'home.features.f2_title': "Безопасная оплата",
    'home.features.f2_desc': "Все платежи защищены и безопасны.",
    'home.features.f3_title': "Поддержка 24/7",
    'home.features.f3_desc': "Готовы помочь с любым вопросом.",
    'home.features.f4_title': "Комфортные автобусы",
    'home.features.f4_desc': "Все наши автобусы современные и оснащены удобствами.",
    'auth.login.title': "Добро пожаловать",
    'auth.login.subtitle': "Введите данные для входа в систему",
    'auth.login.email_tab': "Через Email",
    'auth.login.phone_tab': "Через телефон",
    'auth.login.email_label': "Email адрес",
    'auth.login.phone_label': "Номер телефона",
    'auth.login.password_label': "Пароль",
    'auth.login.forgot_password': "Забыли пароль?",
    'auth.login.btn': "Войти",
    'auth.login.google_btn': "Войти через Google",
    'auth.login.no_account': "Нет аккаунта?",
    'auth.login.register_link': "Зарегистрироваться",
    'auth.login.send_code': "Отправить код",
    'auth.login.verify_code': "Подтвердить код",
    'auth.login.code_label': "Код подтверждения",
    'auth.login.back': "Назад",
    'auth.register.title': "Регистрация",
    'auth.register.subtitle': "Введите данные для создания нового аккаунта",
    'auth.register.name_label': "Имя и фамилия",
    'auth.register.role_label': "Кем вы хотите зарегистрироваться?",
    'auth.register.role_user': "Пассажир",
    'auth.register.role_driver': "Водитель",
    'auth.register.btn': "Зарегистрироваться",
    'auth.register.has_account': "У вас есть аккаунт?",
    'auth.register.login_link': "Войти",
    'profile.title': "Личный кабинет",
    'profile.subtitle': "Ваши данные и билеты",
    'profile.tabs.tickets': "Активные билеты",
    'profile.tabs.history': "История",
    'profile.tabs.newsletter': "Рассылка",
    'profile.tabs.settings': "Настройки",
    'profile.tickets.empty': "У вас пока нет активных билетов",
    'profile.tickets.find': "Найти рейсы",
    'profile.history.empty': "История поездок пуста",
    'profile.settings.name': "Имя и фамилия",
    'profile.settings.phone': "Номер телефона",
    'profile.settings.email': "Email",
    'profile.settings.save': "Сохранить",
    'profile.settings.success': "Данные сохранены!",
    'profile.ticket.download': "Скачать",
    'profile.ticket.cancel': "Отменить",
    'profile.ticket.status.pending': "В ожидании",
    'profile.ticket.status.confirmed': "Подтвержден",
    'profile.ticket.status.cancelled': "Отменен",
    'profile.ticket.seat': "Место",
    'profile.ticket.price': "Цена",
    'profile.ticket.date': "Покупка",
    'profile.driver.rides': "Мои рейсы",
    'profile.driver.add_ride': "Добавить рейс",
    'profile.driver.stop_sharing': "Остановить",
    'home.faq.q1': "Как отменить билет?",
    'home.faq.a1': "Перейдите в раздел 'Активные билеты' в вашем профиле, выберите нужный билет и нажмите кнопку отмены. Ваши средства будут возвращены в течение 3 рабочих дней.",
    'home.faq.q2': "Каковы правила провоза багажа?",
    'home.faq.a2': "На каждого пассажира разрешено до 20 кг бесплатного багажа. За дополнительный багаж взимается отдельная плата.",
    'home.faq.q3': "Как связаться с водителем?",
    'home.faq.a3': "После покупки билета номер телефона водителя будет виден в информации о билете в вашем профиле.",
    'home.faq.q4': "Как производится оплата?",
    'home.faq.a4': "Вы можете оплатить онлайн через системы Payme, Click, UzCard и Humo.",
    'home.faq.q5': "Можно ли забронировать место заранее?",
    'home.faq.a5': "Да, в процессе выбора рейса вы можете выбрать и забронировать любое свободное место.",
    'home.faq.q6': "Есть ли скидки для детей?",
    'home.faq.a6': "Для детей до 7 лет предоставляется скидка 50%. Для детей старше 7 лет оплачивается полная стоимость билета.",
    'home.footer.desc': "Самые удобные, быстрые и безопасные автобусные рейсы из Хорезма в Ташкент и обратно.",
    'home.footer.links': "Быстрые ссылки",
    'home.footer.contact': "Контакты",
    'home.footer.newsletter': "Подпишитесь на новости",
    'home.footer.newsletter_desc': "Узнавайте первыми о скидках и новых рейсах.",
    'home.footer.rights': "Все права защищены.",
    'home.footer.privacy': "Политика конфиденциальности",
    'home.footer.terms': "Публичная оферта",
    'admin.dashboard': 'Дашборд',
    'admin.rides': 'Рейсы',
    'admin.drivers': 'Водители',
    'admin.users': 'Пользователи',
    'admin.messages': 'Сообщения',
    'admin.chats': 'Чаты',
    'admin.reviews': 'Отзывы',
    'admin.payments': 'Платежи',
    'admin.settings': 'Настройки',
    'admin.faqs': 'FAQ',
    'admin.logout': 'Выйти',
    'admin.rides.new': 'Новый рейс',
    'admin.rides.edit': 'Редактировать рейс',
    'admin.rides.add': 'Добавить рейс',
    'admin.drivers.new': 'Новый водитель',
    'admin.drivers.edit': 'Редактировать водителя',
    'admin.drivers.add': 'Добавить водителя',
    'admin.users.new': 'Новый пользователь',
    'admin.users.edit': 'Редактировать пользователя',
    'admin.users.add': 'Добавить пользователя',
    'admin.faqs.new': 'Новый вопрос',
    'admin.faqs.edit': 'Редактировать вопрос',
    'admin.faqs.add': 'Добавить вопрос',
    'admin.common.save': 'Сохранить',
    'admin.common.delete': 'Удалить',
    'admin.common.cancel': 'Отмена',
    'admin.common.actions': 'Действия',
    'admin.common.status': 'Статус',
    'admin.common.date': 'Дата',
    'admin.common.price': 'Цена',
    'admin.users.search': 'Поиск пользователя...',
    'admin.users.role_user': 'Пользователь',
    'admin.users.role_driver': 'Водитель',
    'admin.users.role_admin': 'Админ',
    'admin.users.send_message': 'Написать сообщение',
    'admin.chats.create_error': 'Ошибка при создании чата',
    'admin.chats.title': 'Чат с пользователями',
    'admin.chats.search': 'Поиск чатов...',
    'admin.chats.input_placeholder': 'Напишите сообщение...',
    'admin.chats.select_user': 'Выберите пользователя слева, чтобы начать чат',
    'admin.chats.online': 'В сети',
    'admin.chats.you_admin': 'Вы (Админ)',
    'admin.chats.email_not_found': 'Email не указан',
    'home.reviews.empty': "Пока нет отзывов",
    'home.reviews.login_to_review': "Войдите, чтобы оставить отзыв",
    'home.faq.subtitle': "Подробные ответы на все ваши вопросы",
    'home.contact.success_desc': "Ваше сообщение успешно отправлено. Мы ответим вам в ближайшее время.",
    'home.hero.search': "Поиск рейсов",
    'admin.notifications': 'Уведомления',
    'admin.notifications.new': 'Новое уведомление',
    'admin.notifications.send': 'Отправить',
    'admin.notifications.cancel': 'Отмена',
    'admin.notifications.form_title': 'Отправить новое уведомление',
    'admin.notifications.title_label': 'Заголовок',
    'admin.notifications.message_label': 'Текст сообщения',
    'admin.notifications.target_label': 'Кому отправить',
    'admin.notifications.target_all': 'Всем пользователям',
    'admin.notifications.target_newcomers': 'Новичкам (0 билетов или &lt; 2 дней)',
    'admin.notifications.empty': 'Отправленных уведомлений пока нет.',
    'admin.notifications.sent_title': 'Отправленные уведомления',
  },
  en: {
    'menu.home': 'Home',
    'menu.blog': 'Blog',
    'menu.profile': 'Profile',
    'menu.admin': 'Admin Panel',
    'menu.stats': 'Statistics',
    'menu.help': 'Help',
    'menu.logout': 'Logout',
    'menu.login': 'Login',
    'menu.title': 'Menu',
    'menu.subtitle': 'TezChipta Services',
    'lang.uz': 'Uzbek',
    'lang.ru': 'Russian',
    'lang.en': 'English',
    'lang.select': 'Select Language',
    'home.hero.title': 'From Khorezm to Tashkent',
    'home.hero.highlight': 'fast, convenient and cheap',
    'home.hero.action': 'buy a ticket!',
    'home.hero.subtitle': 'Choose a seat in 1 minute, contact the driver, buy a ticket online.',
    'home.search.from_label': 'From',
    'home.search.to_label': 'To',
    'home.search.date_label': 'Date',
    'home.search.all_cities': 'All cities',
    'home.search.btn': 'Search',
    'home.search.from': 'From where?',
    'home.search.to': 'To where?',
    'home.search.today': 'Today',
    'home.search.tomorrow': 'Tomorrow',
    'home.search.weekly': 'Weekly',
    'home.rides.title': 'Available Rides',
    'home.rides.empty': 'No rides available yet',
    'home.booking.btn': 'Get Ticket',
    'home.faq.title': 'Frequently Asked Questions',
    'profile.track_bus': 'Track Bus',
    'profile.driver_controls': 'Driver Controls',
    'profile.share_location': 'Share Location',
    'profile.bus_location_title': 'Where is the bus?',
    'profile.live_tracking': 'Real-time tracking',
    'profile.live_status': 'Live',
    'profile.location_not_found': 'Location not found',
    'profile.driver_not_sharing': 'The driver has not shared their location yet.',
    'profile.loading_map': 'Loading map...',
    'home.rides.subtitle': "Choose a convenient time and book your seat.",
    'home.rides.loading': "Searching for rides...",
    'home.rides.recommended': "Recommended",
    'home.rides.price': "Ticket price",
    'home.rides.departure': "Departure",
    'home.rides.arrival': "Arrival",
    'home.rides.seats_left': "seats left",
    'home.rides.book_btn': "Select seat",
    'home.rides.driver': "Driver",
    'home.rides.bus_info': "Bus info",
    'home.rides.amenities': "Amenities",
    'home.rides.wifi': "Wi-Fi",
    'home.rides.ac': "AC",
    'home.rides.tv': "TV",
    'home.rides.socket': "Socket",
    'home.rides.water': "Water",
    'home.rides.select_seat': "Select a seat",
    'home.rides.selected_seat': "Selected seat",
    'home.rides.continue': "Continue",
    'home.rides.cancel': "Cancel",
    'home.payment.title': "Select payment method",
    'home.payment.card': "Card (Stripe)",
    'home.payment.manual': "Card transfer",
    'home.payment.manual_desc': "Transfer money to the card number below and upload the receipt",
    'home.payment.upload_receipt': "Upload receipt",
    'home.payment.confirm': "Confirm payment",
    'home.payment.success': "Payment completed successfully!",
    'home.payment.processing': "Verifying payment...",
    'home.payment.error': "Payment error",
    'home.contact.title': "Contact us",
    'home.contact.subtitle': "Have questions? Write to us",
    'home.contact.name': "Your name",
    'home.contact.contact': "Phone or Email",
    'home.contact.message': "Your message",
    'home.contact.send': "Send",
    'home.contact.success': "Your message has been sent!",
    'home.reviews.title': "Customer reviews",
    'home.reviews.subtitle': "What our customers say about our services?",
    'home.reviews.add': "Leave a review",
    'home.reviews.rating': "Rating",
    'home.reviews.comment': "Your review",
    'home.reviews.submit': "Submit",
    'home.stats.passengers': "Passengers",
    'home.stats.routes': "Routes",
    'home.stats.drivers': "Drivers",
    'home.stats.experience': "Years of experience",
    'home.footer.about': "TezChipta - Safe and comfortable bus rides across Uzbekistan.",
    'home.features.title': "Why choose us?",
    'home.features.subtitle': "Advantages of traveling with us",
    'home.features.f1_title': "Fast and convenient",
    'home.features.f1_desc': "Buy tickets from home in 1 minute.",
    'home.features.f2_title': "Secure payment",
    'home.features.f2_desc': "All payments are protected and secure.",
    'home.features.f3_title': "24/7 Support",
    'home.features.f3_desc': "We are ready to help with any question.",
    'home.features.f4_title': "Comfortable buses",
    'home.features.f4_desc': "All our buses are modern and equipped with amenities.",
    'auth.login.title': "Welcome back",
    'auth.login.subtitle': "Enter your details to log in",
    'auth.login.email_tab': "Via Email",
    'auth.login.phone_tab': "Via Phone",
    'auth.login.email_label': "Email address",
    'auth.login.phone_label': "Phone number",
    'auth.login.password_label': "Password",
    'auth.login.forgot_password': "Forgot password?",
    'auth.login.btn': "Log in",
    'auth.login.google_btn': "Log in with Google",
    'auth.login.no_account': "Don't have an account?",
    'auth.login.register_link': "Register",
    'auth.login.send_code': "Send code",
    'auth.login.verify_code': "Verify code",
    'auth.login.code_label': "Verification code",
    'auth.login.back': "Back",
    'auth.register.title': "Register",
    'auth.register.subtitle': "Enter your details to create a new account",
    'auth.register.name_label': "Full name",
    'auth.register.role_label': "Register as",
    'auth.register.role_user': "Passenger",
    'auth.register.role_driver': "Driver",
    'auth.register.btn': "Register",
    'auth.register.has_account': "Already have an account?",
    'auth.register.login_link': "Log in",
    'profile.title': "Personal Cabinet",
    'profile.subtitle': "Your details and tickets",
    'profile.tabs.tickets': "Active tickets",
    'profile.tabs.history': "History",
    'profile.tabs.newsletter': "Newsletter",
    'profile.tabs.settings': "Settings",
    'profile.tickets.empty': "You have no active tickets yet",
    'profile.tickets.find': "Find rides",
    'profile.history.empty': "Trip history is empty",
    'profile.settings.name': "Full name",
    'profile.settings.phone': "Phone number",
    'profile.settings.email': "Email",
    'profile.settings.save': "Save",
    'profile.settings.success': "Data saved!",
    'profile.ticket.download': "Download",
    'profile.ticket.cancel': "Cancel",
    'profile.ticket.status.pending': "Pending",
    'profile.ticket.status.confirmed': "Confirmed",
    'profile.ticket.status.cancelled': "Cancelled",
    'profile.ticket.seat': "Seat",
    'profile.ticket.price': "Price",
    'profile.ticket.date': "Purchase",
    'profile.driver.rides': "My rides",
    'profile.driver.add_ride': "Add ride",
    'profile.driver.stop_sharing': "Stop",
    'home.faq.q1': "How can I cancel a ticket?",
    'home.faq.a1': "Go to the 'Active Tickets' section in your profile, select the desired ticket, and click the cancel button. Your funds will be returned within 3 business days.",
    'home.faq.q2': "What are the baggage rules?",
    'home.faq.a2': "Up to 20 kg of free baggage is allowed per passenger. A separate fee applies for additional luggage.",
    'home.faq.q3': "How can I contact the driver?",
    'home.faq.a3': "After purchasing a ticket, the driver's phone number will be visible in the ticket details in your profile.",
    'home.faq.q4': "How is payment made?",
    'home.faq.a4': "You can pay online via Payme, Click, UzCard, and Humo systems.",
    'home.faq.q5': "Can I book a seat in advance?",
    'home.faq.a5': "Yes, during the ride selection process, you can choose and book any available seat you prefer.",
    'home.faq.q6': "Is there a discount for children?",
    'home.faq.a6': "There is a 50% discount for children under 7 years old. For children over 7 years old, the full ticket price applies.",
    'home.footer.desc': "The most comfortable, fast, and safe bus rides from Khorezm to Tashkent and back.",
    'home.footer.links': "Quick Links",
    'home.footer.contact': "Contact",
    'home.footer.newsletter': "Subscribe to our newsletter",
    'home.footer.newsletter_desc': "Be the first to know about discounts and new rides.",
    'home.footer.rights': "All rights reserved.",
    'home.footer.privacy': "Privacy Policy",
    'home.footer.terms': "Terms of Service",
    'admin.dashboard': 'Dashboard',
    'admin.rides': 'Rides',
    'admin.drivers': 'Drivers',
    'admin.users': 'Users',
    'admin.messages': 'Messages',
    'admin.chats': 'Chats',
    'admin.reviews': 'Reviews',
    'admin.payments': 'Payments',
    'admin.settings': 'Settings',
    'admin.faqs': 'FAQ',
    'admin.logout': 'Logout',
    'admin.rides.new': 'New Ride',
    'admin.rides.edit': 'Edit Ride',
    'admin.rides.add': 'Add Ride',
    'admin.drivers.new': 'New Driver',
    'admin.drivers.edit': 'Edit Driver',
    'admin.drivers.add': 'Add Driver',
    'admin.users.new': 'New User',
    'admin.users.edit': 'Edit User',
    'admin.users.add': 'Add User',
    'admin.faqs.new': 'New FAQ',
    'admin.faqs.edit': 'Edit FAQ',
    'admin.faqs.add': 'Add FAQ',
    'admin.common.save': 'Save',
    'admin.common.delete': 'Delete',
    'admin.common.cancel': 'Cancel',
    'admin.common.actions': 'Actions',
    'admin.common.status': 'Status',
    'admin.common.date': 'Date',
    'admin.common.price': 'Price',
    'admin.users.search': 'Search user...',
    'admin.users.role_user': 'User',
    'admin.users.role_driver': 'Driver',
    'admin.users.role_admin': 'Admin',
    'admin.users.send_message': 'Send message',
    'admin.chats.create_error': 'Error creating chat',
    'admin.chats.title': 'Chat with users',
    'admin.chats.search': 'Search chats...',
    'admin.chats.input_placeholder': 'Type a message...',
    'admin.chats.select_user': 'Select a user from the left to start chatting',
    'admin.chats.online': 'Online',
    'admin.chats.you_admin': 'You (Admin)',
    'admin.chats.email_not_found': 'Email not available',
    'home.reviews.empty': "No reviews yet",
    'home.reviews.login_to_review': "Log in to leave a review",
    'home.faq.subtitle': "Answers to all your questions",
    'home.contact.success_desc': "Your message has been sent successfully. We will contact you soon.",
    'home.hero.search': "Search for rides",
    'admin.notifications': 'Notifications',
    'admin.notifications.new': 'New Notification',
    'admin.notifications.send': 'Send',
    'admin.notifications.cancel': 'Cancel',
    'admin.notifications.form_title': 'Send New Notification',
    'admin.notifications.title_label': 'Title',
    'admin.notifications.message_label': 'Message Text',
    'admin.notifications.target_label': 'Send to',
    'admin.notifications.target_all': 'To All Users',
    'admin.notifications.target_newcomers': 'To Newcomers (0 tickets or &lt; 2 days)',
    'admin.notifications.empty': 'No notifications sent yet.',
    'admin.notifications.sent_title': 'Sent Notifications',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'uz';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
