import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'uz' | 'ru' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  uz: {
    'menu.home': 'Bosh sahifa',
    'menu.blog': 'Blog',
    'menu.profile': 'Profil',
    'menu.admin': 'Boshqaruv paneli',
    'menu.stats': 'Statistika',
    'menu.help': 'Yordam',
    'menu.logout': 'Chiqish',
    'menu.login': 'Kirish',
    'menu.title': 'Menyu',
    'menu.subtitle': 'TezChipta xizmatlari',
    'lang.uz': "O'zbekcha",
    'lang.ru': 'Русский',
    'lang.en': 'English',
    'lang.select': 'Tilni tanlang',
    'home.hero.title': "Xorazmdan Toshkentga",
    'home.hero.highlight': "tez, qulay va arzon",
    'home.hero.action': "chipta sotib oling!",
    'home.hero.subtitle': "1 daqiqada o'rindiq tanlang, haydovchi bilan bog'laning, chiptani onlayn sotib oling.",
    'home.search.from_label': 'Qayerdan',
    'home.search.to_label': 'Qayerga',
    'home.search.date_label': 'Sana',
    'home.search.all_cities': 'Barcha shaharlar',
    'home.search.btn': 'Qidirish',
    'home.search.from': 'Qayerdan?',
    'home.search.to': 'Qayerga?',
    'home.search.today': 'Bugun',
    'home.search.tomorrow': 'Ertaga',
    'home.search.weekly': 'Haftalik',
    'home.rides.title': 'Mavjud qatnovlar',
    'home.rides.empty': 'Hozircha qatnovlar mavjud emas',
    'home.booking.btn': 'Chipta olish',
    'home.faq.title': 'Ko\'p beriladigan savollar',
    'profile.track_bus': 'Kuzatish',
    'profile.driver_controls': 'Haydovchi boshqaruvi',
    'profile.share_location': 'Manzilni ulashish',
    'profile.bus_location_title': 'Avtobus qayerda?',
    'profile.live_tracking': 'Real vaqt rejimida kuzatish',
    'profile.live_status': 'Jonli efir',
    'profile.location_not_found': 'Manzil aniqlanmadi',
    'profile.driver_not_sharing': 'Haydovchi hali o\'z manzilini ulashmadi.',
    'profile.loading_map': 'Xarita yuklanmoqda...',
    'home.rides.subtitle': "Eng mos vaqtni tanlang va o'z o'rningizni band qiling.",
    'home.rides.loading': "Qatnovlar qidirilmoqda...",
    'home.rides.recommended': "Tavsiya etiladi",
    'home.rides.price': "Chipta narxi",
    'home.rides.departure': "Jo'nash",
    'home.rides.arrival': "Kelish",
    'home.rides.seats_left': "ta o'rin qoldi",
    'home.rides.book_btn': "O'rindiq tanlash",
    'home.rides.driver': "Haydovchi",
    'home.rides.bus_info': "Avtobus ma'lumotlari",
    'home.rides.amenities': "Qulayliklar",
    'home.rides.wifi': "Wi-Fi",
    'home.rides.ac': "Konditsioner",
    'home.rides.tv': "TV",
    'home.rides.socket': "Rozetka",
    'home.rides.water': "Suv",
    'home.rides.select_seat': "O'rindiqni tanlang",
    'home.rides.selected_seat': "Tanlangan o'rindiq",
    'home.rides.continue': "Davom etish",
    'home.rides.cancel': "Bekor qilish",
    'home.payment.title': "To'lov usulini tanlang",
    'home.payment.card': "Karta orqali (Stripe)",
    'home.payment.manual': "Karta raqamiga o'tkazish",
    'home.payment.manual_desc': "Quyidagi karta raqamiga pul o'tkazing va chekni yuklang",
    'home.payment.upload_receipt': "Chekni yuklash",
    'home.payment.confirm': "To'lovni tasdiqlash",
    'home.payment.success': "To'lov muvaffaqiyatli amalga oshirildi!",
    'home.payment.processing': "To'lov tekshirilmoqda...",
    'home.payment.error': "To'lovda xatolik yuz berdi",
    'home.contact.title': "Biz bilan bog'lanish",
    'home.contact.subtitle': "Savollaringiz bormi? Bizga yozing",
    'home.contact.name': "Ismingiz",
    'home.contact.contact': "Telefon yoki Email",
    'home.contact.message': "Xabaringiz",
    'home.contact.send': "Yuborish",
    'home.contact.success': "Xabaringiz yuborildi!",
    'home.reviews.title': "Mijozlar fikrlari",
    'home.reviews.subtitle': "Bizning xizmatlarimiz haqida mijozlarimiz nima deydi?",
    'home.reviews.add': "Fikr qoldirish",
    'home.reviews.rating': "Baho",
    'home.reviews.comment': "Fikringiz",
    'home.reviews.submit': "Yuborish",
    'home.stats.passengers': "Yo'lovchilar",
    'home.stats.routes': "Qatnovlar",
    'home.stats.drivers': "Haydovchilar",
    'home.stats.experience': "Yillik tajriba",
    'home.footer.about': "TezChipta - O'zbekiston bo'ylab xavfsiz va qulay avtobus qatnovlari.",
    'home.footer.links': "Foydali havolalar",
    'home.footer.contact': "Aloqa",
    'home.footer.rights': "Barcha huquqlar himoyalangan.",
    'home.features.title': "Nega aynan biz?",
    'home.features.subtitle': "Biz bilan sayohat qilishning afzalliklari",
    'home.features.f1_title': "Tez va qulay",
    'home.features.f1_desc': "Chiptalarni uydan chiqmasdan, 1 daqiqada xarid qiling.",
    'home.features.f2_title': "Xavfsiz to'lov",
    'home.features.f2_desc': "Barcha to'lovlar himoyalangan va xavfsiz.",
    'home.features.f3_title': "24/7 Qo'llab-quvvatlash",
    'home.features.f3_desc': "Har qanday savol bo'yicha yordam berishga tayyormiz.",
    'home.features.f4_title': "Qulay avtobuslar",
    'home.features.f4_desc': "Barcha avtobuslarimiz zamonaviy va qulayliklarga ega.",
    'auth.login.title': "Xush kelibsiz",
    'auth.login.subtitle': "Tizimga kirish uchun ma'lumotlaringizni kiriting",
    'auth.login.email_tab': "Email orqali",
    'auth.login.phone_tab': "Telefon orqali",
    'auth.login.email_label': "Email manzil",
    'auth.login.phone_label': "Telefon raqam",
    'auth.login.password_label': "Parol",
    'auth.login.forgot_password': "Parolni unutdingizmi?",
    'auth.login.btn': "Tizimga kirish",
    'auth.login.google_btn': "Google orqali kirish",
    'auth.login.no_account': "Hisobingiz yo'qmi?",
    'auth.login.register_link': "Ro'yxatdan o'tish",
    'auth.login.send_code': "Kodni yuborish",
    'auth.login.verify_code': "Kodni tasdiqlash",
    'auth.login.code_label': "Tasdiqlash kodi",
    'auth.login.back': "Orqaga",
    'auth.register.title': "Ro'yxatdan o'tish",
    'auth.register.subtitle': "Yangi hisob yaratish uchun ma'lumotlarni kiriting",
    'auth.register.name_label': "Ism va familiya",
    'auth.register.role_label': "Kim sifatida ro'yxatdan o'tmoqchisiz?",
    'auth.register.role_user': "Yo'lovchi",
    'auth.register.role_driver': "Haydovchi",
    'auth.register.btn': "Ro'yxatdan o'tish",
    'auth.register.has_account': "Hisobingiz bormi?",
    'auth.register.login_link': "Tizimga kirish",
    'profile.title': "Shaxsiy kabinet",
    'profile.subtitle': "Ma'lumotlaringiz va chiptalaringiz",
    'profile.tabs.tickets': "Faol chiptalar",
    'profile.tabs.history': "Tarix",
    'profile.tabs.settings': "Sozlamalar",
    'profile.tickets.empty': "Sizda hozircha faol chiptalar yo'q",
    'profile.tickets.find': "Qatnovlarni izlash",
    'profile.history.empty': "Sayohatlar tarixi bo'sh",
    'profile.settings.name': "Ism va familiya",
    'profile.settings.phone': "Telefon raqam",
    'profile.settings.email': "Email",
    'profile.settings.save': "Saqlash",
    'profile.settings.success': "Ma'lumotlar saqlandi!",
    'profile.ticket.download': "Yuklab olish",
    'profile.ticket.cancel': "Bekor qilish",
    'profile.ticket.status.pending': "Kutilmoqda",
    'profile.ticket.status.confirmed': "Tasdiqlangan",
    'profile.ticket.status.cancelled': "Bekor qilingan",
    'profile.ticket.seat': "O'rindiq",
    'profile.ticket.price': "Narxi",
    'profile.ticket.date': "Xarid",
    'profile.driver.rides': "Mening qatnovlarim",
    'profile.driver.add_ride': "Qatnov qo'shish",
    'profile.driver.stop_sharing': "To'xtatish",
    'home.faq.q1': "Chiptani qanday bekor qilish mumkin?",
    'home.faq.a1': "Profilingizdagi 'Faol chiptalar' bo'limiga kirib, kerakli chiptani tanlang va bekor qilish tugmasini bosing. Mablag'ingiz 3 ish kunida qaytariladi.",
    'home.faq.q2': "Bagaj qoidalari qanday?",
    'home.faq.a2': "Har bir yo'lovchi uchun 20 kg gacha bepul bagaj ruxsat etiladi. Qo'shimcha yuk uchun alohida to'lov amalga oshiriladi.",
    'home.faq.q3': "Haydovchi bilan qanday bog'lanish mumkin?",
    'home.faq.a3': "Chipta sotib olganingizdan so'ng, haydovchining telefon raqami profilingizdagi chipta ma'lumotlarida ko'rinadi.",
    'home.faq.q4': "To'lov qanday amalga oshiriladi?",
    'home.faq.a4': "To'lovlarni Payme, Click, UzCard va Humo tizimlari orqali onlayn tarzda amalga oshirishingiz mumkin.",
    'home.faq.q5': "O'rindiqni oldindan band qilish mumkinmi?",
    'home.faq.a5': "Ha, reysni tanlash jarayonida bo'sh o'rindiqlardan o'zingizga ma'qulini tanlab band qilishingiz mumkin.",
    'home.faq.q6': "Bolalar uchun chegirma bormi?",
    'home.faq.a6': "7 yoshgacha bo'lgan bolalar uchun 50% chegirma mavjud. 7 yoshdan yuqori bolalar uchun to'liq chipta narxi hisoblanadi.",
    'home.footer.desc': "Xorazmdan Toshkentga va qaytish yo'nalishida eng qulay, tez va xavfsiz avtobus qatnovlari.",
    'home.footer.newsletter': "Yangiliklarga obuna bo'ling",
    'home.footer.newsletter_desc': "Chegirmalar va yangi reyslar haqida birinchilardan bo'lib xabardor bo'ling.",
    'home.footer.privacy': "Maxfiylik siyosati",
    'home.footer.terms': "Ommaviy oferta",
    'admin.dashboard': 'Dashboard',
    'admin.rides': 'Qatnovlar',
    'admin.drivers': 'Haydovchilar',
    'admin.users': 'Foydalanuvchilar',
    'admin.messages': 'Xabarlar',
    'admin.chats': 'Chatlar',
    'admin.reviews': 'Fikrlar',
    'admin.payments': "To'lovlar",
    'admin.settings': 'Sozlamalar',
    'admin.faqs': 'FAQ',
    'admin.logout': 'Chiqish',
    'admin.newsletter': 'Newsletter',
    'admin.newsletter.subscribers': 'Obunachilar',
    'admin.newsletter.send': 'Xabar yuborish',
    'admin.newsletter.subject': 'Mavzu',
    'admin.newsletter.content': 'Xabar matni',
    'admin.newsletter.export': 'Excelga yuklash',
    'admin.newsletter.history': 'Yuborilgan xabarlar',
    'admin.newsletter.success': 'Xabar muvaffaqiyatli yuborildi!',
    'admin.newsletter.error': 'Xabar yuborishda xatolik yuz berdi',
    'admin.notifications': 'Bildirishnomalar',
    'admin.notifications.send': 'Bildirishnoma yuborish',
    'admin.notifications.title': 'Nom',
    'admin.notifications.type': 'Tur',
    'admin.notifications.details': 'Batafsil',
    'admin.notifications.target': 'Kimga',
    'admin.notifications.target.all': 'Hamma',
    'admin.notifications.target.new': 'Yangi foydalanuvchilar',
    'admin.notifications.success': 'Bildirishnoma muvaffaqiyatli yuborildi!',
    'admin.notifications.history': 'Yuborilgan bildirishnomalar',
    'notifications.new': 'Yangi bildirishnoma',
    'notifications.empty': 'Bildirishnomalar yo\'q',
    'notifications.mark_read': 'O\'qilgan deb belgilash',
    'profile.newsletter': 'Newsletter',
    'profile.newsletter.subscribed': 'Siz yangiliklarga obuna bo\'lgansiz',
    'profile.newsletter.not_subscribed': 'Siz hali yangiliklarga obuna bo\'lmagansiz',
    'profile.newsletter.subscribe_btn': 'Obuna bo\'lish',
    'profile.newsletter.unsubscribe_btn': 'Obunani bekor qilish',
    'profile.newsletter.history': 'Yuborilgan xabarlar',
    'profile.newsletter.empty': 'Hozircha xabarlar yo\'q',
    'admin.rides.new': 'Yangi qatnov',
    'admin.rides.edit': 'Qatnovni tahrirlash',
    'admin.rides.add': "Qatnov qo'shish",
    'admin.drivers.new': 'Yangi haydovchi',
    'admin.drivers.edit': 'Haydovchini tahrirlash',
    'admin.drivers.add': "Haydovchi qo'shish",
    'admin.users.new': 'Yangi foydalanuvchi',
    'admin.users.edit': 'Foydalanuvchini tahrirlash',
    'admin.users.add': "Foydalanuvchi qo'shish",
    'admin.faqs.new': 'Yangi savol',
    'admin.faqs.edit': 'Savolni tahrirlash',
    'admin.faqs.add': "Savol qo'shish",
    'admin.common.save': 'Saqlash',
    'admin.common.delete': "O'chirish",
    'admin.common.cancel': 'Bekor qilish',
    'admin.common.actions': 'Amallar',
    'admin.common.status': 'Holati',
    'admin.common.date': 'Sana',
    'admin.common.price': 'Narxi',
    'admin.users.search': 'Foydalanuvchi qidirish...',
    'admin.users.role_user': 'Foydalanuvchi',
    'admin.users.role_driver': 'Haydovchi',
    'admin.users.role_admin': 'Admin',
    'admin.users.send_message': 'Xabar yozish',
    'admin.chats.create_error': 'Chat yaratishda xatolik yuz berdi',
    'admin.chats.title': 'Foydalanuvchilar bilan chat',
    'admin.chats.search': 'Chatlarni qidirish...',
    'admin.chats.input_placeholder': 'Xabar yozing...',
    'admin.chats.select_user': 'Suhbatni boshlash uchun chap tomondan foydalanuvchini tanlang',
    'admin.chats.online': 'Onlayn',
    'admin.chats.you_admin': 'Siz (Admin)',
    'admin.chats.email_not_found': 'Email mavjud emas',
    'admin.rides.from': 'Qayerdan',
    'admin.rides.to': 'Qayerga',
    'admin.rides.date': 'Sana',
    'admin.rides.status': 'Status',
    'admin.rides.sort': 'Saralash',
    'admin.rides.route': 'Yo\'nalish',
    'admin.rides.driver': 'Haydovchi',
    'admin.rides.type_price': 'Turi / Narxi',
    'admin.rides.active': 'Faol',
    'admin.rides.completed': 'Yakunlangan',
    'admin.rides.cancelled': 'Bekor qilingan',
    'admin.rides.all': 'Barchasi',
    'admin.rides.today': 'Bugun',
    'admin.rides.tomorrow': 'Ertaga',
    'admin.rides.weekly': 'Haftalik',
    'admin.rides.time_asc': 'Vaqt (oldinroq)',
    'admin.rides.time_desc': 'Vaqt (kechroq)',
    'admin.rides.price_asc': 'Narx (arzonroq)',
    'admin.rides.price_desc': 'Narx (qimmatroq)',
    'admin.rides.rating_desc': 'Reyting (yuqori)',
    'admin.rides.unknown_driver': 'Noma\'lum',
    'admin.rides.save': 'Saqlash',
    'admin.rides.image': 'Rasm',
    'admin.rides.placeholder_from': 'Toshkent...',
    'admin.rides.placeholder_to': 'Samarqand...',
    'home.contact.success_desc': "Tez orada siz bilan bog'lanamiz.",
    'home.contact.contact_placeholder': 'info@example.com yoki +998...',
    'home.contact.name_placeholder': 'Falonchi Pistonchiyev',
    'home.contact.message_label': 'Xabar',
    'home.contact.message_placeholder': 'Qanday yordam bera olamiz?',
    'home.safe_payment': '100% Xavfsiz',
    'home.reviews.login_to_review': 'Fikr qoldirish uchun tizimga kiring',
    'home.reviews.empty': 'Hozircha fikrlar mavjud emas.',
    'home.faq.subtitle': "Eng ko'p beriladigan savollarga javoblar. Agar o'zingizni qiziqtirgan savolga javob topmasangiz, biz bilan bog'laning.",
    'blog.title': 'TezChipta Blogi',
    'blog.subtitle': 'Sayohatlar, yangiliklar va haydovchilarimizdan foydali maslahatlar.',
    'blog.search_placeholder': 'Postlarni qidirish...',
    'blog.all_tags': 'Barchasi',
    'blog.read_more': 'Batafsil',
    'blog.no_posts': 'Postlar topilmadi',
    'blog.no_posts_desc': "Qidiruv so'rovini o'zgartirib ko'ring.",
    'blog.add_post': "Post qo'shish",
    'blog.edit_post': 'Postni tahrirlash',
    'blog.new_post': "Yangi post qo'shish",
    'blog.form.title': 'Sarlavha',
    'blog.form.title_placeholder': 'Post sarlavhasini kiriting',
    'blog.form.image': 'Rasm URL (ixtiyoriy)',
    'blog.form.tags': 'Teglar (vergul bilan ajrating)',
    'blog.form.tags_placeholder': 'sayohat, yangilik, maslahat',
    'blog.form.content': 'Mazmuni',
    'blog.form.content_placeholder': 'Post mazmunini yozing...',
    'blog.form.publish': 'Chop etish',
    'blog.form.save': 'Saqlash',
    'blog.delete_confirm': "Haqiqatan ham ushbu postni o'chirmoqchimisiz?",
    'stats.title': 'Platforma Statistikasi',
    'stats.top_ticket': 'Eng ko\'p sotib olingan chipta',
    'stats.active_time': 'Eng ko\'p faol bo\'lingan vaqt',
    'stats.top_location': 'Eng ko\'p kirilgan joylashuv',
    'stats.no_data': 'Hali ma\'lumot yo\'q',
    'stats.ai_analysis_title': 'Foydalanuvchilar statistikasi AI tahlili',
    'stats.ai_loading': 'AI tahlil tayyorlanmoqda...',
    'stats.ai_error': 'AI analizni yuklashda xatolik yuz berdi.',
    'stats.growth_chart': 'Foydalanuvchilar o\'sish dinamikasi',
    'stats.ai_prompt': 'Iltimos, ushbu statistika haqida qisqa va professional tahlil bering. O\'sish va potentsial yaxshilanishlarga e\'tibor qarating. Qisqa bo\'lsin (2-3 jumlada).',
    'terms.title': 'Foydalanish Shartlari',
    'terms.last_update': 'Oxirgi yangilanish',
    'terms.section1.title': '1. Shartlarni qabul qilish',
    'terms.section1.content': '"TezChipta" platformasidan foydalanish orqali siz ushbu Foydalanish shartlariga to\'liq rozilik bildirasiz. Agar siz ushbu shartlarga rozi bo\'lmasangiz, iltimos, xizmatdan foydalanmang.',
    'terms.section2.title': '2. Xizmat tavsifi',
    'terms.section2.content': '"TezChipta" — bu avtobus chiptalarini onlayn bron qilish va sotib olish xizmatidir. Biz tashuvchilar va yo\'lovchilar o\'rtasida vositachilik qilamiz.',
    'terms.section2.list1': 'Xizmatdan faqat qonuniy maqsadlarda foydalanish mumkin.',
    'terms.section2.list2': 'Foydalanuvchi taqdim etgan ma\'lumotlarning to\'g\'riligi uchun o\'zi mas\'uldir.',
    'terms.section2.list3': 'Chiptalarni qaytarish va almashtirish tashuvchining qoidalariga muvofiq amalga oshiriladi.',
    'terms.section3.title': '3. Mas\'uliyatni cheklash',
    'terms.section3.content': '"TezChipta" tashuvchilar tomonidan sodir etilgan kechikishlar, reyslarning bekor qilinishi yoki yo\'ldagi boshqa ko\'ngilsiz hodisalar uchun bevosita javobgar emas. Biz faqat chipta sotish jarayoni va ma\'lumotlarning to\'g\'ri yetkazilishi uchun mas\'ulmiz.',
    'terms.section4.title': '4. To\'lovlar va qaytarish',
    'terms.section4.content': 'Barcha to\'lovlar O\'zbekiston Respublikasi milliy valyutasida amalga oshiriladi. Chiptani bekor qilishda xizmat haqi ushlab qolinishi mumkin. Qaytarish muddati to\'lov tizimi qoidalariga bog\'liq.',
    'terms.contact.title': 'Savollaringiz bormi?',
    'terms.contact.desc': 'Foydalanish shartlari bo\'yicha qo\'shimcha ma\'lumot olish uchun biz bilan bog\'laning:',
    'privacy.title': 'Maxfiylik Siyosati',
    'privacy.section1.title': '1. Ma\'lumotlarni yig\'ish',
    'privacy.section1.content': '"TezChipta" xizmatidan foydalanganingizda, biz sizga xizmat ko\'rsatish uchun zarur bo\'lgan quyidagi ma\'lumotlarni yig\'ishimiz mumkin:',
    'privacy.section1.list1': 'Shaxsiy ma\'lumotlar: Ism, familiya, telefon raqami va email manzili.',
    'privacy.section1.list2': 'Xizmat ma\'lumotlari: Chipta buyurtmalari tarixi, to\'lov ma\'lumotlari (to\'lov tizimlari orqali).',
    'privacy.section1.list3': 'Texnik ma\'lumotlar: IP-manzil, brauzer turi va qurilma haqidagi ma\'lumotlar.',
    'privacy.section2.title': '2. Ma\'lumotlardan foydalanish',
    'privacy.section2.content': 'Biz yig\'ilgan ma\'lumotlardan quyidagi maqsadlarda foydalanamiz:',
    'privacy.section2.list1': 'Chiptalarni bron qilish va rasmiylashtirish qoidalarini ta\'minlash.',
    'privacy.section2.list2': 'Siz bilan bog\'lanish va xizmatdagi o\'zgarishlar haqida xabar berish.',
    'privacy.section2.list3': 'Xizmat sifatini yaxshilash va foydalanuvchi tajribasini tahlil qilish.',
    'privacy.section2.list4': 'Xavfsizlikni ta\'minlash va firibgarlikning oldini olish.',
    'privacy.section3.title': '3. Ma\'lumotlar xavfsizligi',
    'privacy.section3.content': 'Sizning ma\'lumotlaringiz xavfsizligi biz uchun ustuvor vazifadir. Biz ma\'lumotlarni ruxsatsiz kirish, o\'zgartirish yoki yo\'q qilishdan himoya qilish uchun zamonaviy shifrlash usullari va xavfsizlik protokollaridan foydalanamiz.',
    'privacy.section4.title': '4. Uchinchi tomon xizmatlari',
    'privacy.section4.content': 'Biz ma\'lumotlaringizni uchinchi tomonlarga sotmaymiz. Biroq, xizmat ko\'rsatish uchun zarur bo\'lgan hollarda (masalan, to\'lov tizimlari yoki SMS xizmatlari) ma\'lumotlar ishonchli hamkorlarimiz bilan baham ko\'rilishi mumkin.',
    'privacy.contact.title': 'Bog\'lanish',
    'privacy.contact.desc': 'Maxfiylik siyosati bo\'yicha savollaringiz bo\'lsa, biz bilan bog\'laning:',
  },
  ru: {
    'menu.home': 'Главная',
    'menu.blog': 'Блог',
    'menu.profile': 'Профиль',
    'menu.admin': 'Панель управления',
    'menu.stats': 'Статистика',
    'menu.help': 'Помощь',
    'menu.logout': 'Выйти',
    'menu.login': 'Войти',
    'menu.title': 'Меню',
    'menu.subtitle': 'Услуги TezChipta',
    'lang.uz': 'Узбекский',
    'lang.ru': 'Русский',
    'lang.en': 'Английский',
    'lang.select': 'Выберите язык',
    'home.hero.title': 'Из Хорезма в Ташкент',
    'home.hero.highlight': 'быстро, удобно и дешево',
    'home.hero.action': 'купите билет!',
    'home.hero.subtitle': 'Выберите место за 1 минуту, свяжитесь с водителем, купите билет онлайн.',
    'home.search.from_label': 'Откуда',
    'home.search.to_label': 'Куда',
    'home.search.date_label': 'Дата',
    'home.search.all_cities': 'Все города',
    'home.search.btn': 'Поиск',
    'home.search.from': 'Откуда?',
    'home.search.to': 'Куда?',
    'home.search.today': 'Сегодня',
    'home.search.tomorrow': 'Завтра',
    'home.search.weekly': 'На неделю',
    'home.rides.title': 'Доступные рейсы',
    'home.rides.empty': 'Рейсов пока нет',
    'home.booking.btn': 'Купить билет',
    'home.faq.title': 'Часто задаваемые вопросы',
    'profile.track_bus': 'Отследить',
    'profile.driver_controls': 'Управление водителем',
    'profile.share_location': 'Поделиться местоположением',
    'profile.bus_location_title': 'Где автобус?',
    'profile.live_tracking': 'Отслеживание в реальном времени',
    'profile.live_status': 'В прямом эфире',
    'profile.location_not_found': 'Местоположение не определено',
    'profile.driver_not_sharing': 'Водитель еще не поделился своим местоположением.',
    'profile.loading_map': 'Загрузка карты...',
    'home.rides.subtitle': "Выберите удобное время и забронируйте место.",
    'home.rides.loading': "Поиск рейсов...",
    'home.rides.recommended': "Рекомендуется",
    'home.rides.price': "Цена билета",
    'home.rides.departure': "Отправление",
    'home.rides.arrival': "Прибытие",
    'home.rides.seats_left': "мест осталось",
    'home.rides.book_btn': "Выбрать место",
    'home.rides.driver': "Водитель",
    'home.rides.bus_info': "Информация об автобусе",
    'home.rides.amenities': "Удобства",
    'home.rides.wifi': "Wi-Fi",
    'home.rides.ac': "Кондиционер",
    'home.rides.tv': "ТВ",
    'home.rides.socket': "Розетка",
    'home.rides.water': "Вода",
    'home.rides.select_seat': "Выберите место",
    'home.rides.selected_seat': "Выбранное место",
    'home.rides.continue': "Продолжить",
    'home.rides.cancel': "Отмена",
    'home.payment.title': "Выберите способ оплаты",
    'home.payment.card': "Картой (Stripe)",
    'home.payment.manual': "Перевод на карту",
    'home.payment.manual_desc': "Переведите деньги на номер карты ниже и загрузите чек",
    'home.payment.upload_receipt': "Загрузить чек",
    'home.payment.confirm': "Подтвердить оплату",
    'home.payment.success': "Оплата успешно завершена!",
    'home.payment.processing': "Проверка оплаты...",
    'home.payment.error': "Ошибка при оплате",
    'home.contact.title': "Свяжитесь с нами",
    'home.contact.subtitle': "Есть вопросы? Напишите нам",
    'home.contact.name': "Ваше имя",
    'home.contact.contact': "Телефон или Email",
    'home.contact.message': "Ваше сообщение",
    'home.contact.send': "Отправить",
    'home.contact.success': "Ваше сообщение отправлено!",
    'home.reviews.title': "Отзывы клиентов",
    'home.reviews.subtitle': "Что говорят наши клиенты о наших услугах?",
    'home.reviews.add': "Оставить отзыв",
    'home.reviews.rating': "Оценка",
    'home.reviews.comment': "Ваш отзыв",
    'home.reviews.submit': "Отправить",
    'home.stats.passengers': "Пассажиры",
    'home.stats.routes': "Рейсы",
    'home.stats.drivers': "Водители",
    'home.stats.experience': "Лет опыта",
    'home.footer.about': "TezChipta - Безопасные и комфортные автобусные рейсы по Узбекистану.",
    'home.footer.links': "Полезные ссылки",
    'home.footer.contact': "Контакты",
    'home.footer.rights': "Все права защищены.",
    'home.features.title': "Почему мы?",
    'home.features.subtitle': "Преимущества путешествия с нами",
    'home.features.f1_title': "Быстро и удобно",
    'home.features.f1_desc': "Покупайте билеты не выходя из дома за 1 минуту.",
    'home.features.f2_title': "Безопасная оплата",
    'home.features.f2_desc': "Все платежи защищены и безопасны.",
    'home.features.f3_title': "Поддержка 24/7",
    'home.features.f3_desc': "Готовы помочь с любым вопросом.",
    'home.features.f4_title': "Комфортные автобусы",
    'home.features.f4_desc': "Все наши автобусы современные и оснащены удобствами.",
    'auth.login.title': "Добро пожаловать",
    'auth.login.subtitle': "Введите данные для входа в систему",
    'auth.login.email_tab': "Через Email",
    'auth.login.phone_tab': "Через телефон",
    'auth.login.email_label': "Email адрес",
    'auth.login.phone_label': "Номер телефона",
    'auth.login.password_label': "Пароль",
    'auth.login.forgot_password': "Забыли пароль?",
    'auth.login.btn': "Войти",
    'auth.login.google_btn': "Войти через Google",
    'auth.login.no_account': "Нет аккаунта?",
    'auth.login.register_link': "Зарегистрироваться",
    'auth.login.send_code': "Отправить код",
    'auth.login.verify_code': "Подтвердить код",
    'auth.login.code_label': "Код подтверждения",
    'auth.login.back': "Назад",
    'auth.register.title': "Регистрация",
    'auth.register.subtitle': "Введите данные для создания нового аккаунта",
    'auth.register.name_label': "Имя и фамилия",
    'auth.register.role_label': "Кем вы хотите зарегистрироваться?",
    'auth.register.role_user': "Пассажир",
    'auth.register.role_driver': "Водитель",
    'auth.register.btn': "Зарегистрироваться",
    'auth.register.has_account': "У вас есть аккаунт?",
    'auth.register.login_link': "Войти",
    'profile.title': "Личный кабинет",
    'profile.subtitle': "Ваши данные и билеты",
    'profile.tabs.tickets': "Активные билеты",
    'profile.tabs.history': "История",
    'profile.tabs.settings': "Настройки",
    'profile.tickets.empty': "У вас пока нет активных билетов",
    'profile.tickets.find': "Найти рейсы",
    'profile.history.empty': "История поездок пуста",
    'profile.settings.name': "Имя и фамилия",
    'profile.settings.phone': "Номер телефона",
    'profile.settings.email': "Email",
    'profile.settings.save': "Сохранить",
    'profile.settings.success': "Данные сохранены!",
    'profile.ticket.download': "Скачать",
    'profile.ticket.cancel': "Отменить",
    'profile.ticket.status.pending': "В ожидании",
    'profile.ticket.status.confirmed': "Подтвержден",
    'profile.ticket.status.cancelled': "Отменен",
    'profile.ticket.seat': "Место",
    'profile.ticket.price': "Цена",
    'profile.ticket.date': "Покупка",
    'profile.driver.rides': "Мои рейсы",
    'profile.driver.add_ride': "Добавить рейс",
    'profile.driver.stop_sharing': "Остановить",
    'home.faq.q1': "Как отменить билет?",
    'home.faq.a1': "Перейдите в раздел 'Активные билеты' в вашем профиле, выберите нужный билет и нажмите кнопку отмены. Ваши средства будут возвращены в течение 3 рабочих дней.",
    'home.faq.q2': "Каковы правила провоза багажа?",
    'home.faq.a2': "На каждого пассажира разрешено до 20 кг бесплатного багажа. За дополнительный багаж взимается отдельная плата.",
    'home.faq.q3': "Как связаться с водителем?",
    'home.faq.a3': "После покупки билета номер телефона водителя будет виден в информации о билете в вашем профиле.",
    'home.faq.q4': "Как производится оплата?",
    'home.faq.a4': "Вы можете оплатить онлайн через системы Payme, Click, UzCard и Humo.",
    'home.faq.q5': "Можно ли забронировать место заранее?",
    'home.faq.a5': "Да, в процессе выбора рейса вы можете выбрать и забронировать любое свободное место.",
    'home.faq.q6': "Есть ли скидки для детей?",
    'home.faq.a6': "Для детей до 7 лет предоставляется скидка 50%. Для детей старше 7 лет оплачивается полная стоимость билета.",
    'home.footer.desc': "Самые удобные, быстрые и безопасные автобусные рейсы из Хорезма в Ташкент и обратно.",
    'home.footer.newsletter': "Подпишитесь на новости",
    'home.footer.newsletter_desc': "Узнавайте первыми о скидках и новых рейсах.",
    'home.footer.privacy': "Политика конфиденциальности",
    'home.footer.terms': "Публичная оферта",
    'admin.dashboard': 'Дашборд',
    'admin.rides': 'Рейсы',
    'admin.drivers': 'Водители',
    'admin.users': 'Пользователи',
    'admin.messages': 'Сообщения',
    'admin.chats': 'Чаты',
    'admin.reviews': 'Отзывы',
    'admin.payments': 'Платежи',
    'admin.settings': 'Настройки',
    'admin.faqs': 'FAQ',
    'admin.logout': 'Выйти',
    'admin.newsletter': 'Рассылка',
    'admin.newsletter.subscribers': 'Подписчики',
    'admin.newsletter.send': 'Отправить сообщение',
    'admin.newsletter.subject': 'Тема',
    'admin.newsletter.content': 'Текст сообщения',
    'admin.newsletter.export': 'Экспорт в Excel',
    'admin.newsletter.history': 'История рассылок',
    'admin.newsletter.success': 'Сообщение успешно отправлено!',
    'admin.newsletter.error': 'Ошибка при отправке сообщения',
    'admin.notifications': 'Уведомления',
    'admin.notifications.send': 'Отправить уведомление',
    'admin.notifications.title': 'Название',
    'admin.notifications.type': 'Тип',
    'admin.notifications.details': 'Подробности',
    'admin.notifications.target': 'Кому',
    'admin.notifications.target.all': 'Всем',
    'admin.notifications.target.new': 'Новым пользователям',
    'admin.notifications.success': 'Уведомление успешно отправлено!',
    'admin.notifications.history': 'История уведомлений',
    'notifications.new': 'Новое уведомление',
    'notifications.empty': 'Нет уведомлений',
    'notifications.mark_read': 'Отметить как прочитанное',
    'profile.newsletter': 'Рассылка',
    'profile.newsletter.subscribed': 'Вы подписаны на новости',
    'profile.newsletter.not_subscribed': 'Вы еще не подписаны на новости',
    'profile.newsletter.subscribe_btn': 'Подписаться',
    'profile.newsletter.unsubscribe_btn': 'Отписаться',
    'profile.newsletter.history': 'История сообщений',
    'profile.newsletter.empty': 'Сообщений пока нет',
    'admin.rides.new': 'Новый рейс',
    'admin.rides.edit': 'Редактировать рейс',
    'admin.rides.add': 'Добавить рейс',
    'admin.drivers.new': 'Новый водитель',
    'admin.drivers.edit': 'Редактировать водителя',
    'admin.drivers.add': 'Добавить водителя',
    'admin.users.new': 'Новый пользователь',
    'admin.users.edit': 'Редактировать пользователя',
    'admin.users.add': 'Добавить пользователя',
    'admin.faqs.new': 'Новый вопрос',
    'admin.faqs.edit': 'Редактировать вопрос',
    'admin.faqs.add': 'Добавить вопрос',
    'admin.common.save': 'Сохранить',
    'admin.common.delete': 'Удалить',
    'admin.common.cancel': 'Отмена',
    'admin.common.actions': 'Действия',
    'admin.common.status': 'Статус',
    'admin.common.date': 'Дата',
    'admin.common.price': 'Цена',
    'admin.users.search': 'Поиск пользователя...',
    'admin.users.role_user': 'Пользователь',
    'admin.users.role_driver': 'Водитель',
    'admin.users.role_admin': 'Админ',
    'admin.users.send_message': 'Написать сообщение',
    'admin.chats.create_error': 'Ошибка при создании чата',
    'admin.chats.title': 'Чат с пользователями',
    'admin.chats.search': 'Поиск чатов...',
    'admin.chats.input_placeholder': 'Напишите сообщение...',
    'admin.chats.select_user': 'Выберите пользователя слева, чтобы начать чат',
    'admin.chats.online': 'В сети',
    'admin.chats.you_admin': 'Вы (Админ)',
    'admin.chats.email_not_found': 'Email не указан',
    'admin.rides.from': 'Откуда',
    'admin.rides.to': 'Куда',
    'admin.rides.date': 'Дата',
    'admin.rides.status': 'Статус',
    'admin.rides.sort': 'Сортировка',
    'admin.rides.route': 'Маршрут',
    'admin.rides.driver': 'Водитель',
    'admin.rides.type_price': 'Тип / Цена',
    'admin.rides.active': 'Активный',
    'admin.rides.completed': 'Завершен',
    'admin.rides.cancelled': 'Отменен',
    'admin.rides.all': 'Все',
    'admin.rides.today': 'Сегодня',
    'admin.rides.tomorrow': 'Завтра',
    'admin.rides.weekly': 'Еженедельно',
    'admin.rides.time_asc': 'Время (раньше)',
    'admin.rides.time_desc': 'Время (позже)',
    'admin.rides.price_asc': 'Цена (дешевле)',
    'admin.rides.price_desc': 'Цена (дороже)',
    'admin.rides.rating_desc': 'Рейтинг (высокий)',
    'admin.rides.unknown_driver': 'Неизвестно',
    'admin.rides.save': 'Сохранить',
    'admin.rides.image': 'Изображение',
    'admin.rides.placeholder_from': 'Ташкент...',
    'admin.rides.placeholder_to': 'Самарканд...',
    'home.contact.success_desc': 'Мы свяжемся с вами в ближайшее время.',
    'home.contact.contact_placeholder': 'info@example.com или +998...',
    'home.contact.name_placeholder': 'Иван Иванов',
    'home.contact.message_label': 'Сообщение',
    'home.contact.message_placeholder': 'Чем мы можем помочь?',
    'home.safe_payment': '100% Безопасно',
    'home.reviews.login_to_review': 'Войдите, чтобы оставить отзыв',
    'home.reviews.empty': 'Отзывов пока нет.',
    'home.faq.subtitle': 'Ответы на часто задаваемые вопросы. Если вы не нашли ответ на свой вопрос, свяжитесь с нами.',
    'blog.title': 'Блог TezChipta',
    'blog.subtitle': 'Путешествия, новости и полезные советы от наших водителей.',
    'blog.search_placeholder': 'Поиск постов...',
    'blog.all_tags': 'Все',
    'blog.read_more': 'Подробнее',
    'blog.no_posts': 'Посты не найдены',
    'blog.no_posts_desc': 'Попробуйте изменить поисковый запрос.',
    'blog.add_post': 'Добавить пост',
    'blog.edit_post': 'Редактировать пост',
    'blog.new_post': 'Добавить новый пост',
    'blog.form.title': 'Заголовок',
    'blog.form.title_placeholder': 'Введите заголовок поста',
    'blog.form.image': 'URL изображения (опционально)',
    'blog.form.tags': 'Теги (через запятую)',
    'blog.form.tags_placeholder': 'путешествие, новости, совет',
    'blog.form.content': 'Содержание',
    'blog.form.content_placeholder': 'Напишите содержание поста...',
    'blog.form.publish': 'Опубликовать',
    'blog.form.save': 'Сохранить',
    'blog.delete_confirm': 'Вы уверены, что хотите удалить этот пост?',
    'stats.title': 'Статистика платформы',
    'stats.top_ticket': 'Самый покупаемый билет',
    'stats.active_time': 'Самое активное время',
    'stats.top_location': 'Самая посещаемая локация',
    'stats.no_data': 'Данных пока нет',
    'stats.ai_analysis_title': 'ИИ анализ статистики пользователей',
    'stats.ai_loading': 'Подготовка ИИ анализа...',
    'stats.ai_error': 'Ошибка при загрузке ИИ анализа.',
    'stats.growth_chart': 'Динамика роста пользователей',
    'stats.ai_prompt': 'Пожалуйста, предоставьте краткий и профессиональный анализ этой статистики. Сосредоточьтесь на росте и потенциальных улучшениях. Будьте кратки (2-3 предложения).',
    'terms.title': 'Условия использования',
    'terms.last_update': 'Последнее обновление',
    'terms.section1.title': '1. Принятие условий',
    'terms.section1.content': 'Используя платформу "TezChipta", вы полностью соглашаетесь с данными Условиями использования. Если вы не согласны с этими условиями, пожалуйста, не пользуйтесь сервисом.',
    'terms.section2.title': '2. Описание услуги',
    'terms.section2.content': '"TezChipta" — это сервис онлайн-бронирования и покупки автобусных билетов. Мы являемся посредниками между перевозчиками и пассажирами.',
    'terms.section2.list1': 'Сервис можно использовать только в законных целях.',
    'terms.section2.list2': 'Пользователь несет ответственность за достоверность предоставленной информации.',
    'terms.section2.list3': 'Возврат и обмен билетов осуществляется в соответствии с правилами перевозчика.',
    'terms.section3.title': '3. Ограничение ответственности',
    'terms.section3.content': '"TezChipta" не несет прямой ответственности за задержки, отмены рейсов или другие неприятные инциденты в пути, совершенные перевозчиками. Мы несем ответственность только за процесс продажи билетов и правильность передачи информации.',
    'terms.section4.title': '4. Платежи и возврат',
    'terms.section4.content': 'Все платежи осуществляются в национальной валюте Республики Узбекистан. При отмене билета может удерживаться сервисный сбор. Срок возврата зависит от правил платежной системы.',
    'terms.contact.title': 'Есть вопросы?',
    'terms.contact.desc': 'Для получения дополнительной информации об условиях использования свяжитесь с нами:',
    'privacy.title': 'Политика конфиденциальности',
    'privacy.section1.title': '1. Сбор данных',
    'privacy.section1.content': 'Когда вы пользуетесь сервисом "TezChipta", мы можем собирать следующие данные, необходимые для предоставления вам услуг:',
    'privacy.section1.list1': 'Персональные данные: Имя, фамилия, номер телефона и адрес электронной почты.',
    'privacy.section1.list2': 'Сервисные данные: История заказов билетов, данные об оплате (через платежные системы).',
    'privacy.section1.list3': 'Технические данные: IP-адрес, тип браузера и информация об устройстве.',
    'privacy.section2.title': '2. Использование данных',
    'privacy.section2.content': 'Мы используем собранные данные для следующих целей:',
    'privacy.section2.list1': 'Обеспечение процесса бронирования и оформления билетов.',
    'privacy.section2.list2': 'Связь с вами и информирование об изменениях в сервисе.',
    'privacy.section2.list3': 'Улучшение качества обслуживания и анализ пользовательского опыта.',
    'privacy.section2.list4': 'Обеспечение безопасности и предотвращение мошенничества.',
    'privacy.section3.title': '3. Безопасность данных',
    'privacy.section3.content': 'Безопасность ваших данных является для нас приоритетом. Мы используем современные методы шифрования и протоколы безопасности для защиты данных от несанкционированного доступа, изменения или уничтожения.',
    'privacy.section4.title': '4. Сторонние сервисы',
    'privacy.section4.content': 'Мы не продаем ваши данные третьим лицам. Однако в случаях, необходимых для предоставления услуг (например, платежные системы или SMS-сервисы), данные могут быть переданы нашим доверенным партнерам.',
    'privacy.contact.title': 'Связь',
    'privacy.contact.desc': 'Если у вас есть вопросы по политике конфиденциальности, свяжитесь с нами:',
  },
  en: {
    'menu.home': 'Home',
    'menu.blog': 'Blog',
    'menu.profile': 'Profile',
    'menu.admin': 'Admin Panel',
    'menu.stats': 'Statistics',
    'menu.help': 'Help',
    'menu.logout': 'Logout',
    'menu.login': 'Login',
    'menu.title': 'Menu',
    'menu.subtitle': 'TezChipta Services',
    'lang.uz': 'Uzbek',
    'lang.ru': 'Russian',
    'lang.en': 'English',
    'lang.select': 'Select Language',
    'home.hero.title': 'From Khorezm to Tashkent',
    'home.hero.highlight': 'fast, convenient and cheap',
    'home.hero.action': 'buy a ticket!',
    'home.hero.subtitle': 'Choose a seat in 1 minute, contact the driver, buy a ticket online.',
    'home.search.from_label': 'From',
    'home.search.to_label': 'To',
    'home.search.date_label': 'Date',
    'home.search.all_cities': 'All cities',
    'home.search.btn': 'Search',
    'home.search.from': 'From where?',
    'home.search.to': 'To where?',
    'home.search.today': 'Today',
    'home.search.tomorrow': 'Tomorrow',
    'home.search.weekly': 'Weekly',
    'home.rides.title': 'Available Rides',
    'home.rides.empty': 'No rides available yet',
    'home.booking.btn': 'Get Ticket',
    'home.faq.title': 'Frequently Asked Questions',
    'profile.track_bus': 'Track Bus',
    'profile.driver_controls': 'Driver Controls',
    'profile.share_location': 'Share Location',
    'profile.bus_location_title': 'Where is the bus?',
    'profile.live_tracking': 'Real-time tracking',
    'profile.live_status': 'Live',
    'profile.location_not_found': 'Location not found',
    'profile.driver_not_sharing': 'The driver has not shared their location yet.',
    'profile.loading_map': 'Loading map...',
    'home.rides.subtitle': "Choose a convenient time and book your seat.",
    'home.rides.loading': "Searching for rides...",
    'home.rides.recommended': "Recommended",
    'home.rides.price': "Ticket price",
    'home.rides.departure': "Departure",
    'home.rides.arrival': "Arrival",
    'home.rides.seats_left': "seats left",
    'home.rides.book_btn': "Select seat",
    'home.rides.driver': "Driver",
    'home.rides.bus_info': "Bus info",
    'home.rides.amenities': "Amenities",
    'home.rides.wifi': "Wi-Fi",
    'home.rides.ac': "AC",
    'home.rides.tv': "TV",
    'home.rides.socket': "Socket",
    'home.rides.water': "Water",
    'home.rides.select_seat': "Select a seat",
    'home.rides.selected_seat': "Selected seat",
    'home.rides.continue': "Continue",
    'home.rides.cancel': "Cancel",
    'home.payment.title': "Select payment method",
    'home.payment.card': "Card (Stripe)",
    'home.payment.manual': "Card transfer",
    'home.payment.manual_desc': "Transfer money to the card number below and upload the receipt",
    'home.payment.upload_receipt': "Upload receipt",
    'home.payment.confirm': "Confirm payment",
    'home.payment.success': "Payment completed successfully!",
    'home.payment.processing': "Verifying payment...",
    'home.payment.error': "Payment error",
    'home.contact.title': "Contact us",
    'home.contact.subtitle': "Have questions? Write to us",
    'home.contact.name': "Your name",
    'home.contact.contact': "Phone or Email",
    'home.contact.message': "Your message",
    'home.contact.send': "Send",
    'home.contact.success': "Your message has been sent!",
    'home.reviews.title': "Customer reviews",
    'home.reviews.subtitle': "What our customers say about our services?",
    'home.reviews.add': "Leave a review",
    'home.reviews.rating': "Rating",
    'home.reviews.comment': "Your review",
    'home.reviews.submit': "Submit",
    'home.stats.passengers': "Passengers",
    'home.stats.routes': "Routes",
    'home.stats.drivers': "Drivers",
    'home.stats.experience': "Years of experience",
    'home.footer.about': "TezChipta - Safe and comfortable bus rides across Uzbekistan.",
    'home.footer.links': "Useful links",
    'home.footer.contact': "Contact",
    'home.footer.rights': "All rights reserved.",
    'home.features.title': "Why choose us?",
    'home.features.subtitle': "Advantages of traveling with us",
    'home.features.f1_title': "Fast and convenient",
    'home.features.f1_desc': "Buy tickets from home in 1 minute.",
    'home.features.f2_title': "Secure payment",
    'home.features.f2_desc': "All payments are protected and secure.",
    'home.features.f3_title': "24/7 Support",
    'home.features.f3_desc': "We are ready to help with any question.",
    'home.features.f4_title': "Comfortable buses",
    'home.features.f4_desc': "All our buses are modern and equipped with amenities.",
    'auth.login.title': "Welcome back",
    'auth.login.subtitle': "Enter your details to log in",
    'auth.login.email_tab': "Via Email",
    'auth.login.phone_tab': "Via Phone",
    'auth.login.email_label': "Email address",
    'auth.login.phone_label': "Phone number",
    'auth.login.password_label': "Password",
    'auth.login.forgot_password': "Forgot password?",
    'auth.login.btn': "Log in",
    'auth.login.google_btn': "Log in with Google",
    'auth.login.no_account': "Don't have an account?",
    'auth.login.register_link': "Register",
    'auth.login.send_code': "Send code",
    'auth.login.verify_code': "Verify code",
    'auth.login.code_label': "Verification code",
    'auth.login.back': "Back",
    'auth.register.title': "Register",
    'auth.register.subtitle': "Enter your details to create a new account",
    'auth.register.name_label': "Full name",
    'auth.register.role_label': "Register as",
    'auth.register.role_user': "Passenger",
    'auth.register.role_driver': "Driver",
    'auth.register.btn': "Register",
    'auth.register.has_account': "Already have an account?",
    'auth.register.login_link': "Log in",
    'profile.title': "Personal Cabinet",
    'profile.subtitle': "Your details and tickets",
    'profile.tabs.tickets': "Active tickets",
    'profile.tabs.history': "History",
    'profile.tabs.settings': "Settings",
    'profile.tickets.empty': "You have no active tickets yet",
    'profile.tickets.find': "Find rides",
    'profile.history.empty': "Trip history is empty",
    'profile.settings.name': "Full name",
    'profile.settings.phone': "Phone number",
    'profile.settings.email': "Email",
    'profile.settings.save': "Save",
    'profile.settings.success': "Data saved!",
    'profile.ticket.download': "Download",
    'profile.ticket.cancel': "Cancel",
    'profile.ticket.status.pending': "Pending",
    'profile.ticket.status.confirmed': "Confirmed",
    'profile.ticket.status.cancelled': "Cancelled",
    'profile.ticket.seat': "Seat",
    'profile.ticket.price': "Price",
    'profile.ticket.date': "Purchase",
    'profile.driver.rides': "My rides",
    'profile.driver.add_ride': "Add ride",
    'profile.driver.stop_sharing': "Stop",
    'home.faq.q1': "How can I cancel a ticket?",
    'home.faq.a1': "Go to the 'Active Tickets' section in your profile, select the desired ticket, and click the cancel button. Your funds will be returned within 3 business days.",
    'home.faq.q2': "What are the baggage rules?",
    'home.faq.a2': "Up to 20 kg of free baggage is allowed per passenger. A separate fee applies for additional luggage.",
    'home.faq.q3': "How can I contact the driver?",
    'home.faq.a3': "After purchasing a ticket, the driver's phone number will be visible in the ticket details in your profile.",
    'home.faq.q4': "How is payment made?",
    'home.faq.a4': "You can pay online via Payme, Click, UzCard, and Humo systems.",
    'home.faq.q5': "Can I book a seat in advance?",
    'home.faq.a5': "Yes, during the ride selection process, you can choose and book any available seat you prefer.",
    'home.faq.q6': "Is there a discount for children?",
    'home.faq.a6': "There is a 50% discount for children under 7 years old. For children over 7 years old, the full ticket price applies.",
    'home.footer.desc': "The most comfortable, fast, and safe bus rides from Khorezm to Tashkent and back.",
    'home.footer.newsletter': "Subscribe to our newsletter",
    'home.footer.newsletter_desc': "Be the first to know about discounts and new rides.",
    'home.footer.privacy': "Privacy Policy",
    'home.footer.terms': "Terms of Service",
    'admin.dashboard': 'Dashboard',
    'admin.rides': 'Rides',
    'admin.drivers': 'Drivers',
    'admin.users': 'Users',
    'admin.messages': 'Messages',
    'admin.chats': 'Chats',
    'admin.reviews': 'Reviews',
    'admin.payments': 'Payments',
    'admin.settings': 'Settings',
    'admin.faqs': 'FAQ',
    'admin.logout': 'Logout',
    'admin.newsletter': 'Newsletter',
    'admin.newsletter.subscribers': 'Subscribers',
    'admin.newsletter.send': 'Send Message',
    'admin.newsletter.subject': 'Subject',
    'admin.newsletter.content': 'Message Content',
    'admin.newsletter.export': 'Export to Excel',
    'admin.newsletter.history': 'Sent Messages',
    'admin.newsletter.success': 'Message sent successfully!',
    'admin.newsletter.error': 'Error sending message',
    'admin.notifications': 'Notifications',
    'admin.notifications.send': 'Send Notification',
    'admin.notifications.title': 'Name',
    'admin.notifications.type': 'Type',
    'admin.notifications.details': 'Details',
    'admin.notifications.target': 'Target',
    'admin.notifications.target.all': 'All Users',
    'admin.notifications.target.new': 'New Users',
    'admin.notifications.success': 'Notification sent successfully!',
    'admin.notifications.history': 'Notification History',
    'notifications.new': 'New Notification',
    'notifications.empty': 'No notifications',
    'notifications.mark_read': 'Mark as read',
    'profile.newsletter': 'Newsletter',
    'profile.newsletter.subscribed': 'You are subscribed to the newsletter',
    'profile.newsletter.not_subscribed': 'You are not subscribed to the newsletter yet',
    'profile.newsletter.subscribe_btn': 'Subscribe',
    'profile.newsletter.unsubscribe_btn': 'Unsubscribe',
    'profile.newsletter.history': 'Sent Messages',
    'profile.newsletter.empty': 'No messages yet',
    'admin.rides.new': 'New Ride',
    'admin.rides.edit': 'Edit Ride',
    'admin.rides.add': 'Add Ride',
    'admin.drivers.new': 'New Driver',
    'admin.drivers.edit': 'Edit Driver',
    'admin.drivers.add': 'Add Driver',
    'admin.users.new': 'New User',
    'admin.users.edit': 'Edit User',
    'admin.users.add': 'Add User',
    'admin.faqs.new': 'New FAQ',
    'admin.faqs.edit': 'Edit FAQ',
    'admin.faqs.add': 'Add FAQ',
    'admin.common.save': 'Save',
    'admin.common.delete': 'Delete',
    'admin.common.cancel': 'Cancel',
    'admin.common.actions': 'Actions',
    'admin.common.status': 'Status',
    'admin.common.date': 'Date',
    'admin.common.price': 'Price',
    'admin.users.search': 'Search user...',
    'admin.users.role_user': 'User',
    'admin.users.role_driver': 'Driver',
    'admin.users.role_admin': 'Admin',
    'admin.users.send_message': 'Send message',
    'admin.chats.create_error': 'Error creating chat',
    'admin.chats.title': 'Chat with users',
    'admin.chats.search': 'Search chats...',
    'admin.chats.input_placeholder': 'Type a message...',
    'admin.chats.select_user': 'Select a user from the left to start chatting',
    'admin.chats.online': 'Online',
    'admin.chats.you_admin': 'You (Admin)',
    'admin.chats.email_not_found': 'Email not available',
    'admin.rides.from': 'From',
    'admin.rides.to': 'To',
    'admin.rides.date': 'Date',
    'admin.rides.status': 'Status',
    'admin.rides.sort': 'Sort',
    'admin.rides.route': 'Route',
    'admin.rides.driver': 'Driver',
    'admin.rides.type_price': 'Type / Price',
    'admin.rides.active': 'Active',
    'admin.rides.completed': 'Completed',
    'admin.rides.cancelled': 'Cancelled',
    'admin.rides.all': 'All',
    'admin.rides.today': 'Today',
    'admin.rides.tomorrow': 'Tomorrow',
    'admin.rides.weekly': 'Weekly',
    'admin.rides.time_asc': 'Time (earlier)',
    'admin.rides.time_desc': 'Time (later)',
    'admin.rides.price_asc': 'Price (cheaper)',
    'admin.rides.price_desc': 'Price (expensive)',
    'admin.rides.rating_desc': 'Rating (high)',
    'admin.rides.unknown_driver': 'Unknown',
    'admin.rides.save': 'Save',
    'admin.rides.image': 'Image',
    'admin.rides.placeholder_from': 'Tashkent...',
    'admin.rides.placeholder_to': 'Samarkand...',
    'home.contact.success_desc': 'We will contact you shortly.',
    'home.contact.contact_placeholder': 'info@example.com or +998...',
    'home.contact.name_placeholder': 'John Doe',
    'home.contact.message_label': 'Message',
    'home.contact.message_placeholder': 'How can we help you?',
    'home.safe_payment': '100% Secure',
    'home.reviews.login_to_review': 'Log in to leave a review',
    'home.reviews.empty': 'No reviews yet.',
    'home.faq.subtitle': 'Answers to frequently asked questions. If you don\'t find the answer to your question, please contact us.',
    'blog.title': 'TezChipta Blog',
    'blog.subtitle': 'Travels, news, and useful tips from our drivers.',
    'blog.search_placeholder': 'Search posts...',
    'blog.all_tags': 'All',
    'blog.read_more': 'Read More',
    'blog.no_posts': 'No posts found',
    'blog.no_posts_desc': 'Try changing your search query.',
    'blog.add_post': 'Add Post',
    'blog.edit_post': 'Edit Post',
    'blog.new_post': 'Add New Post',
    'blog.form.title': 'Title',
    'blog.form.title_placeholder': 'Enter post title',
    'blog.form.image': 'Image URL (optional)',
    'blog.form.tags': 'Tags (comma separated)',
    'blog.form.tags_placeholder': 'travel, news, tip',
    'blog.form.content': 'Content',
    'blog.form.content_placeholder': 'Write post content...',
    'blog.form.publish': 'Publish',
    'blog.form.save': 'Save',
    'blog.delete_confirm': 'Are you sure you want to delete this post?',
    'stats.title': 'Platform Statistics',
    'stats.top_ticket': 'Most Purchased Ticket',
    'stats.active_time': 'Most Active Time',
    'stats.top_location': 'Most Visited Location',
    'stats.no_data': 'No data yet',
    'stats.ai_analysis_title': 'AI Analysis of User Statistics',
    'stats.ai_loading': 'Preparing AI analysis...',
    'stats.ai_error': 'Error loading AI analysis.',
    'stats.growth_chart': 'User Growth Dynamics',
    'stats.ai_prompt': 'Please provide a short, professional analysis of these statistics. Focus on growth and potential improvements. Keep it concise (2-3 sentences).',
    'terms.title': 'Terms of Service',
    'terms.last_update': 'Last Update',
    'terms.section1.title': '1. Acceptance of Terms',
    'terms.section1.content': 'By using the "TezChipta" platform, you fully agree to these Terms of Service. If you do not agree to these terms, please do not use the service.',
    'terms.section2.title': '2. Service Description',
    'terms.section2.content': '"TezChipta" is an online bus ticket booking and purchase service. We act as intermediaries between carriers and passengers.',
    'terms.section2.list1': 'The service can only be used for legal purposes.',
    'terms.section2.list2': 'The user is responsible for the accuracy of the information provided.',
    'terms.section2.list3': 'Ticket returns and exchanges are carried out in accordance with the carrier\'s rules.',
    'terms.section3.title': '3. Limitation of Liability',
    'terms.section3.content': '"TezChipta" is not directly responsible for delays, flight cancellations, or other unpleasant incidents on the road committed by carriers. We are only responsible for the ticket sales process and the accuracy of information transmission.',
    'terms.section4.title': '4. Payments and Returns',
    'terms.section4.content': 'All payments are made in the national currency of the Republic of Uzbekistan. A service fee may be withheld when canceling a ticket. The return period depends on the rules of the payment system.',
    'terms.contact.title': 'Have questions?',
    'terms.contact.desc': 'For more information on the terms of service, please contact us:',
    'privacy.title': 'Privacy Policy',
    'privacy.section1.title': '1. Data Collection',
    'privacy.section1.content': 'When you use the "TezChipta" service, we may collect the following data necessary to provide you with services:',
    'privacy.section1.list1': 'Personal data: Name, surname, phone number, and email address.',
    'privacy.section1.list2': 'Service data: Ticket order history, payment data (via payment systems).',
    'privacy.section1.list3': 'Technical data: IP address, browser type, and device information.',
    'privacy.section2.title': '2. Use of Data',
    'privacy.section2.content': 'We use the collected data for the following purposes:',
    'privacy.section2.list1': 'Ensuring the booking and ticketing process.',
    'privacy.section2.list2': 'Communicating with you and informing you about changes in the service.',
    'privacy.section2.list3': 'Improving service quality and analyzing user experience.',
    'privacy.section2.list4': 'Ensuring security and preventing fraud.',
    'privacy.section3.title': '3. Data Security',
    'privacy.section3.content': 'The security of your data is a priority for us. We use modern encryption methods and security protocols to protect data from unauthorized access, modification, or destruction.',
    'privacy.section4.title': '4. Third-Party Services',
    'privacy.section4.content': 'We do not sell your data to third parties. However, in cases necessary to provide services (e.g., payment systems or SMS services), data may be shared with our trusted partners.',
    'privacy.contact.title': 'Contact',
    'privacy.contact.desc': 'If you have questions about the privacy policy, please contact us:',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'uz';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
